# 依赖 gravel VM
FROM ghcr.io/graalvm/graalvm-ce:22.3.1
MAINTAINER tengjiqi@gmail.com
# 安装 maven
RUN curl -O https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.9.0/binaries/apache-maven-3.9.0-bin.tar.gz
RUN tar -zxvf apache-maven-3.9.0-bin.tar.gz && mv apache-maven-3.9.0 /opt/powerjob-maven && rm -rf apache-maven-3.9.0-bin.tar.gz
ENV PATH=/opt/powerjob-maven/bin:$PATH
# 安装原生镜像
RUN gu install native-image
# 拷贝源码
COPY . .
# 编译，打原生镜像
RUN mvn clean package -Pnative -DskipTests
# 启动
ENTRYPOINT ["sh", "/app/target/pbot"]